version: '2'
services:
    anguarsampleapplication-app:
        image: anguarsampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://anguarsampleapplication-mysql:3306/anguarsampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=anguarsampleapplication-elasticsearch:9300
        ports:
            - 8080:8080
    anguarsampleapplication-mysql:
        extends:
            file: mysql.yml
            service: anguarsampleapplication-mysql
    anguarsampleapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: anguarsampleapplication-elasticsearch
